# Generated by Django 3.1.6 on 2021-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_auto_20210601_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, 'Lütfen Birini Seçin'), ('hicbiri', 'Belirtmek İstemiyorum'), ('erkek', 'ERKEK'), ('kadın', 'KADIN')], max_length=22, null=True, verbose_name='Cinsiyet'),
        ),
    ]
