# Generated by Django 3.1.6 on 2021-05-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20210601_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[(None, 'Lütfen Birini Seçin'), ('hicbiri', 'Belirtmek İstemiyorum'), ('erkek', 'ERKEK'), ('kadın', 'KADIN')], default='hicbiri', max_length=22, null=True, verbose_name='Cinsiyet'),
        ),
    ]
