# Generated by Django 3.1.6 on 2021-08-09 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastmessaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chtmsg',
            options={'verbose_name_plural': 'Mesajlaşma Sistemi'},
        ),
        migrations.RemoveField(
            model_name='chtmsg',
            name='user',
        ),
        migrations.AddField(
            model_name='chtmsg',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Mesaj Alan kullanıcı'),
        ),
        migrations.AddField(
            model_name='chtmsg',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Mesaj Gönderen Kullanıcı'),
        ),
    ]
