# Generated by Django 3.1.6 on 2021-08-12 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastmessaging', '0002_auto_20210809_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chtroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.SlugField(null=True, unique=True, verbose_name='unique_room')),
                ('owner1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner1', to=settings.AUTH_USER_MODEL, verbose_name='kurucu1')),
                ('owner2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner2', to=settings.AUTH_USER_MODEL, verbose_name='kurucu2')),
            ],
            options={
                'verbose_name_plural': 'Chat Odaları',
            },
        ),
    ]
