# Generated by Django 3.1.6 on 2024-03-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastmessaging', '0003_chtroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chtroom',
            name='room_id',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='unique_room'),
        ),
    ]
