# Generated by Django 3.1.6 on 2021-05-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogmy', '0009_auto_20210514_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blogmy.myblogger'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='icerik',
            field=models.CharField(help_text='Yorum yaz', max_length=250, null=True, verbose_name='Yorum'),
        ),
    ]
