# Generated by Django 3.1.6 on 2021-03-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmy', '0004_auto_20210321_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogger',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
