# Generated by Django 3.1.6 on 2021-02-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Buraya başlık girilir.', max_length=100, null=True, verbose_name='Baslış giriniz')),
                ('icerik', models.TextField(max_length=1000, null=True, verbose_name='içerik giriniz.')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gönderiler',
            },
        ),
    ]
