# Generated by Django 3.1.6 on 2021-02-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogmy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogg',
            new_name='myblogger',
        ),
    ]
