# Generated by Django 3.1.6 on 2021-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmy', '0002_auto_20210201_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogger',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myblogger',
            name='title',
            field=models.CharField(help_text='Buraya başlık girilir.', max_length=100, null=True, verbose_name='Başlık giriniz'),
        ),
    ]
