# Generated by Django 3.1.6 on 2021-07-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogmy', '0013_favoriteblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteblog',
            options={'verbose_name_plural': 'Favorilerim'},
        ),
    ]
