# Generated by Django 3.1.6 on 2021-05-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmy', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
